shellEmulator: true

trustPolicy: no-downgrade

overrides:
  chokidar: 5.0.0
  semver: ^7.0.0
  vite: 8.0.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - simple-git-hooks
  - unrs-resolver
